name: 11 - Working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: false

      target:
        type: environment
        required: true
        description: "Which environment the workflow will target (e.g., 'staging' or 'production')"

      tag:
        type: choice
        description: "Release from which to build and deploy" 
        default: "v3"
        options: [v1,v2,v3]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: | 
          echo "Building from tag ${{ inputs.tag }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        if: ${{ !inputs.dry-run }}
        run: |
          echo "Deploying to ${{ inputs.target }}"
  