name: 14 - Working with Artifacts.

on:
    workflow_dispatch:

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'

            - name: Download Cached Dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: 04-using-actions/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('04-using-actions/react-app/package-lock.json') }} 

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Unit-Tests
              run: npm run test

            - name: Build code
              run: npm run build

            - name: Upload Build Files
              uses: actions/upload-artifact@v4
              with:
                name: app
                path: 04-using-actions/react-app/build

    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Download build files
              uses: actions/download-artifact@v4
              with: 
                name: app
                path: build
            - name: Show Folder Structure
              run: ls -R




              