name: 16 - Working with Environments
run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}

on: 
  workflow_dispatch:
    inputs:
        target-env:
            type: environment
            default: staging
            description: staging env

jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        env: 
            my_env_value: ${{ vars.MY_ENV_VALUE || 'default value' }}
        steps:
            - name: Echo Vars
              run: |
                echo "MY_ENV_VALUE: ${{ env.MY_ENV_VALUE }}" 
